//
//  CoinDetailWorker.swift
//  CoinPrice
//
//  Created by Ratchapol Pattarakanoksiri on 10/3/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoinDetailWorker {
    func loadCoinDetail(parameters: CoinDetailRequest.Parameters, completion: @escaping(Result<CoinDetailResponse>) -> Void) {
        let request = CoinDetailRequest(parameters: parameters)
        NetworkService.shared.sendRequest(request: request, completion: completion)
    }
}
