//
//  CoinDetailModels.swift
//  CoinPrice
//
//  Created by Ratchapol Pattarakanoksiri on 10/3/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CoinDetail {
    // MARK: Use cases

    enum GetCoinDetail {
        struct Request {
        }
        struct Response {
            let coinInfo: CoinInfo?
        }
        struct ViewModel {
            let iconImageUrlString: String?
            let name: String
            let nameColorHex: String?
            let symbol: String
            let price: String
            let marketCap: String
            let detail: String
        }
    }
    
    enum GoToWebsite {
        struct Request {
        }
        struct Response {
            let urlString: String?
        }
        struct ViewModel {
            let url: URL?
        }
    }
}
