//
//  CoinListWorker.swift
//  CoinPrice
//
//  Created by Ratchapol Pattarakanoksiri on 9/3/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoinListWorker {
    func loadCoinList(parameters: CoinListRequest.Parameters, completion: @escaping(Result<CoinListResponse>) -> Void) {
        let request = CoinListRequest(parameters: parameters)
        NetworkService.shared.sendRequest(request: request, completion: completion)
    }
}
