//
//  CoinListRouter.swift
//  CoinPrice
//
//  Created by Ratchapol Pattarakanoksiri on 9/3/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CoinListRoutingLogic {
    func routeToCoinDetail()
}

protocol CoinListDataPassing {
    var dataStore: CoinListDataStore? { get }
}

class CoinListRouter: NSObject, CoinListRoutingLogic, CoinListDataPassing {
    weak var viewController: CoinListViewController?
    var dataStore: CoinListDataStore?

    // MARK: Routing

    func routeToCoinDetail() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "CoinDetailViewController") as! CoinDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToSomewhere(source: CoinListViewController, destination: CoinDetailViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    func passDataToSomewhere(source: CoinListDataStore, destination: inout CoinDetailDataStore) {
        destination.uuid = source.uuid
    }
}
