# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoinPrice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoinPrice
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher', '~> 7.0'

  target 'CoinPriceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinPriceUITests' do
    # Pods for testing
  end

end
